name: PR

on:
  pull_request:
    branches:
    - master

jobs:

  test_install:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install via pip from github
      run: |
        pip install --user -U pip
        pip install wheel
        pip install git+https://github.com/gazprom-neft/seismiqb.git@${{ github.sha }}

    - name: Run 'import' in installed environment
      run: python -c 'import seismiqb'

    - name: Checkout SeismiQB
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run basic tests
      env:
        TESTS_SCRIPTS_DIR: ${{ github.workspace }}/seismiqb/tests/
        PATH_TO_SEISMIQB: '../..'
      run: |
        pip install -U pytest
        pytest -m "not slow" --disable-pytest-warnings -v --pyargs seismiqb.tests
